dep 'dev tools' do
  requires 'python.bin'
  requires 'docker'
  requires 'iterm'
  requires 'heroku'
  requires 'nodejs'
  requires 'clisp.bin'
  requires 'haskell platform'
  requires 'android-sdk.bin'
  requires 'IntelliJ IDEA 14.app'
  requires 'android dev setup'
  requires 'cocoapods.gem'
  requires 'vagrant.bin'
  requires 'vagrant sandbox'
  requires 'git'
  requires 'bash aliases'
  requires 'mono'
  requires 'jq.bin'
end

